title: "Bader's Portfolio"
description: "Showcasing smart home automation, data analytics, and tech solutions."
logo: assets/img/logo.png # Provide a path to your logo if you want to use it
show_downloads: true # No need to show download links unless required
remote_theme: minimal
baseurl: "" # Leave empty unless hosting under a subdirectory
url: "https://bader1919.github.io" # Your GitHub Pages URL



# Navigation links (optional, if using theme-provided navigation)
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Contact"
    url: "/contact.html"

# SEO and meta data
author: "Bader Abdulrahim"
email: "bader.abdulrahim@gmail.com"
