name: Deploy static content to Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages

      - name: Build and deploy
        uses: actions/deploy-pages@v4
